/**
 * @file avrprog_bitbang.h
 * @brief Software SPI (Bit-banging) Interface for AVR ISP Programming
 * 
 * This header defines the interface for bit-banged SPI communication with
 * AVR microcontrollers. Bit-banging provides flexibility to use any GPIO
 * pins for the SPI interface, unlike hardware SPI which is pin-constrained.
 * 
 * Advantages of bit-banging:
 *   - Any GPIO pins can be used
 *   - Easier debugging (can add delays, logging)
 *   - Works when hardware SPI is unavailable or in use
 * 
 * Disadvantages:
 *   - Slower than hardware SPI
 *   - Higher CPU overhead
 *   - Timing less precise
 * 
 * @author MUdroThe1
 * @date 2026
 */

#pragma once

#include <pico/stdlib.h>
#include <stdint.h>
#include <stdbool.h>

/*******************************************************************************
 * Configuration - Bit-bang Pin Definitions
 * 
 * These can be changed to any available GPIO pins.
 * Default pins match the hardware SPI configuration for easy switching.
 ******************************************************************************/
#ifndef BB_MOSI_PIN
#define BB_MOSI_PIN   19    /* Master Out Slave In - data to AVR */
#endif

#ifndef BB_MISO_PIN
#define BB_MISO_PIN   16    /* Master In Slave Out - data from AVR */
#endif

#ifndef BB_SCK_PIN
#define BB_SCK_PIN    18    /* Serial Clock - generated by Pico */
#endif

#ifndef BB_RESET_PIN
#define BB_RESET_PIN  17    /* Active-low reset line */
#endif

/*******************************************************************************
 * Timing Configuration
 ******************************************************************************/

/**
 * @brief Half-period delay in microseconds for SPI clock
 * 
 * This determines the bit-bang SPI clock frequency:
 *   - 10us delay = ~50kHz clock (safe for most AVRs)
 *   - 5us delay  = ~100kHz clock
 *   - 1us delay  = ~500kHz clock
 * 
 * Note: AVR ISP clock should be less than 1/4 of target's system clock.
 * For AVRs with CKDIV8 fuse (1MHz/8 = 125kHz), use at least 10us delay.
 */
#ifndef BB_DELAY_US
#define BB_DELAY_US   10
#endif

/*******************************************************************************
 * Initialization Functions
 ******************************************************************************/

/**
 * @brief Initialize GPIO pins for bit-banged SPI
 * 
 * Configures MOSI, SCK, and RESET as outputs, MISO as input.
 * Sets initial pin states (SCK low, RESET high).
 */
void avr_bitbang_init(void);

/*******************************************************************************
 * SPI Transfer Functions
 ******************************************************************************/

/**
 * @brief Transfer a single byte via bit-banged SPI (Mode 0)
 * 
 * SPI Mode 0 characteristics:
 *   - Clock polarity (CPOL) = 0: Clock idles low
 *   - Clock phase (CPHA) = 0: Data sampled on rising edge
 *   - Data order: MSB first
 * 
 * @param tx_byte Byte to transmit
 * @return Byte received from target
 */
uint8_t avr_bitbang_transfer_byte(uint8_t tx_byte);

/**
 * @brief Transfer multiple bytes via bit-banged SPI
 * 
 * Performs a full-duplex SPI transfer of multiple bytes.
 * TX and RX buffers can be the same for in-place operation.
 * 
 * @param tx_buf Pointer to transmit buffer
 * @param rx_buf Pointer to receive buffer (can be same as tx_buf)
 * @param len Number of bytes to transfer
 */
void avr_bitbang_transfer(const uint8_t *tx_buf, uint8_t *rx_buf, size_t len);

/*******************************************************************************
 * Reset Control Functions
 ******************************************************************************/

/**
 * @brief Assert RESET line (drive low) to hold target in reset
 */
void avr_bitbang_reset_assert(void);

/**
 * @brief Release RESET line (drive high) to let target run
 */
void avr_bitbang_reset_release(void);

/**
 * @brief Pulse the RESET line to restart target
 * 
 * Generates an active-low reset pulse (assert, delay, release).
 */
void avr_bitbang_reset_pulse(void);

/*******************************************************************************
 * Speed Control Functions
 ******************************************************************************/

/**
 * @brief Set the bit-bang SPI clock delay
 * 
 * Allows runtime adjustment of SPI speed. Useful for:
 *   - Slowing down for problematic targets
 *   - Speeding up for faster programming
 * 
 * @param delay_us Half-period delay in microseconds
 */
void avr_bitbang_set_speed(uint32_t delay_us);

/**
 * @brief Get the current bit-bang SPI clock delay
 * 
 * @return Current half-period delay in microseconds
 */
uint32_t avr_bitbang_get_speed(void);

#endif /* AVRPROG_BITBANG_H */
